
package medicasoft.capa1_presentacion;

import javax.swing.JFrame;


public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaMenu() {
       initComponents();
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        gestionarpaciente = new javax.swing.JMenuItem();
        gestionardentista = new javax.swing.JMenuItem();
        gestionarcita = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("ADMINISTRACION");

        gestionarpaciente.setText("GESTIONAR PACIENTE");
        gestionarpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarpacienteActionPerformed(evt);
            }
        });
        jMenu1.add(gestionarpaciente);

        gestionardentista.setText("GESTIONAR DENTISTA");
        gestionardentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionardentistaActionPerformed(evt);
            }
        });
        jMenu1.add(gestionardentista);

        gestionarcita.setText("GESTIONAR CITA");
        gestionarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarcitaActionPerformed(evt);
            }
        });
        jMenu1.add(gestionarcita);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("REPORTES");

        jMenuItem4.setText("GENERAR REPORTES DE CITAS");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("GENERAR REPORTES DE PACIENTES");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("GENERAR REPORTES DE DENTISTAS");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("SEGURIDAD");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("APLICACION");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionarcitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarcitaActionPerformed
         ventana_Registra_Cita formRegistrarCita = new ventana_Registra_Cita(this, true);
        formRegistrarCita.setVisible(true);
    }//GEN-LAST:event_gestionarcitaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void gestionarpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarpacienteActionPerformed
            ventana_Registrar_Paciente formRegistrarPaciente = new ventana_Registrar_Paciente(this, true);
        formRegistrarPaciente.setVisible(true);
    }//GEN-LAST:event_gestionarpacienteActionPerformed

    private void gestionardentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionardentistaActionPerformed
         ventana_Registrar_Dentista formRegistrarDentista = new ventana_Registrar_Dentista(this, true);
        formRegistrarDentista.setVisible(true);
    }//GEN-LAST:event_gestionardentistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem gestionarcita;
    private javax.swing.JMenuItem gestionardentista;
    private javax.swing.JMenuItem gestionarpaciente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
